### ISSUE TITLE
Add support for periods

### ISSUE THREAD

**Issue by leona-ya** [entropia/berechenbarkeit#19]
We want to be able to use one berechenbarkeit instance for multiple reasons, might that be events, general Entropia expenses by year, ...

**Requirements:**
* [ ] An invoice is part of one period
  * think about whether it's necessary to support that one invoice number needs to be split into two periods. Just accounting wise it's theoretical possible I think, but not practical
* [x] Multiple periods might be active at the same time
* [x] Periods should have an active/inactive state (i.e. periods are over at some point)
* [ ] A user should be able to select the period they want to edit. That choice should be remembered
* [ ] All user interfaces should only show objects in the selected period

`Period` might not be the fitting word for that

**Comment by jdreichmann** [comment]
I would propose `Project`, while not perfectly fitting, it comes probably closest to it.

For the model, i would propose having one 'default' project (selectable) and having `project` be a FK on `InvoiceItem`. This would allow being able to split a large bill onto f.ex. a GPNxx project and "entropia" as a ever-ongoing project.

Furthermore, having `project` as part of `InvoiceItem` allows for pre-filling of the 'default' project (selectable in the UI). For reports, one could filter a user-defined subset of all projects.
